export const charList = [
  {
    name: "Ace",
    filename: "ally_01",
  },
  {
    name: "Echo",
    filename: "ally_02",
  },
  {
    name: "Smartie",
    filename: "ally_03",
  },
  {
    name: "Khan",
    filename: "ally_04",
  },
  //   {
  //     name: "Sportsman Ace",
  //     filename: "ally_05",
  //     star: 2,
  //   },
  //   {
  //     name: "Assassin Ace",
  //     filename: "ally_06",
  //     star: 3,
  //   },
  //   {
  //     name: "Pirate Ace",
  //     filename: "ally_07",
  //     feature: 4,
  //     star: 4,
  //     w: 104,
  //     h: 110,
  //     move_frame_num: 8,
  //     wait_frame_num: 8,
  //     attack_frame_num: 10,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 6,
  //     fire_img_frame_num: 1,
  //     attack_fire_frame: 10,
  //     attack_len: 200,
  //     move_speed: 4,
  //     attack_speed: 10,
  //     ap_start: 127,
  //     ap_end: 840,
  //     hp_start: 144,
  //     hp_end: 7200,
  //     nm_start: 360,
  //     nm_end: 810,
  //     max_level: 50,
  //     center_gap_x: 5,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 18,
  //     gagebar_y: -2,
  //   },
  //   {
  //     name: "Captain Ace",
  //     filename: "ally_08",
  //     feature: 4,
  //     star: 5,
  //     w: 99,
  //     h: 118,
  //     move_frame_num: 8,
  //     wait_frame_num: 8,
  //     attack_frame_num: 14,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 8,
  //     fire_img_frame_num: 1,
  //     attack_fire_frame: 7,
  //     attack_len: 350,
  //     move_speed: 4,
  //     attack_speed: 10,
  //     ap_start: 484,
  //     ap_end: 4200,
  //     hp_start: 60,
  //     hp_end: 36000,
  //     nm_start: 710,
  //     nm_end: 1370,
  //     max_level: 60,
  //     center_gap_x: 7,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 13,
  //     gagebar_y: -1,
  //   },
  //   {
  //     name: "Pirate king Ace",
  //     filename: "ally_09",
  //     feature: 4,
  //     star: 6,
  //     w: 107,
  //     h: 126,
  //     move_frame_num: 8,
  //     wait_frame_num: 8,
  //     attack_frame_num: 14,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 8,
  //     fire_img_frame_num: 1,
  //     attack_fire_frame: 7,
  //     attack_len: 350,
  //     move_speed: 4,
  //     attack_speed: 10,
  //     ap_start: 2342,
  //     ap_end: 25200,
  //     hp_start: 3085.5,
  //     hp_end: 216000,
  //     nm_start: 1250,
  //     nm_end: 2160,
  //     max_level: 70,
  //     center_gap_x: 2,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 20,
  //     gagebar_y: 0,
  //   },
  //   {
  //     name: "Headset Echo",
  //     filename: "ally_10",
  //     feature: 1,
  //     star: 2,
  //     w: 124,
  //     h: 114,
  //     move_frame_num: 4,
  //     wait_frame_num: 8,
  //     attack_frame_num: 11,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 8,
  //     fire_img_frame_num: 1,
  //     attack_fire_frame: 9,
  //     attack_len: 200,
  //     move_speed: 7,
  //     attack_speed: 30,
  //     ap_start: 15,
  //     ap_end: 60,
  //     hp_start: 12,
  //     hp_end: 360,
  //     nm_start: 26.666666666666668,
  //     nm_end: 126.66666666666667,
  //     max_level: 30,
  //     center_gap_x: -14,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 48,
  //     gagebar_y: -2,
  //   },
  //   {
  //     name: "Deliveryman Echo",
  //     filename: "ally_11",
  //     feature: 1,
  //     star: 3,
  //     w: 137,
  //     h: 117,
  //     move_frame_num: 4,
  //     wait_frame_num: 8,
  //     attack_frame_num: 11,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 8,
  //     fire_img_frame_num: 1,
  //     attack_fire_frame: 9,
  //     attack_len: 200,
  //     move_speed: 7,
  //     attack_speed: 30,
  //     ap_start: 37.5,
  //     ap_end: 180,
  //     hp_start: 27,
  //     hp_end: 1080,
  //     nm_start: 86.66666666666667,
  //     nm_end: 273.3333333333333,
  //     max_level: 40,
  //     center_gap_x: -14,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 59,
  //     gagebar_y: -2,
  //   },
  //   {
  //     name: "Bee Echo",
  //     filename: "ally_12",
  //     feature: 1,
  //     star: 4,
  //     w: 141,
  //     h: 119,
  //     move_frame_num: 4,
  //     wait_frame_num: 8,
  //     attack_frame_num: 11,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 8,
  //     fire_img_frame_num: 1,
  //     attack_fire_frame: 9,
  //     attack_len: 200,
  //     move_speed: 7,
  //     attack_speed: 30,
  //     ap_start: 109.5,
  //     ap_end: 720,
  //     hp_start: 86,
  //     hp_end: 4320,
  //     nm_start: 220,
  //     nm_end: 520,
  //     max_level: 50,
  //     center_gap_x: -14,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 59,
  //     gagebar_y: -5,
  //   },
  //   {
  //     name: "Bodyguard Echo",
  //     filename: "ally_13",
  //     feature: 1,
  //     star: 5,
  //     w: 155,
  //     h: 137,
  //     move_frame_num: 4,
  //     wait_frame_num: 8,
  //     attack_frame_num: 11,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 8,
  //     fire_img_frame_num: 1,
  //     attack_fire_frame: 9,
  //     attack_len: 200,
  //     move_speed: 7,
  //     attack_speed: 30,
  //     ap_start: 414,
  //     ap_end: 3600,
  //     hp_start: 360,
  //     hp_end: 21600,
  //     nm_start: 453.3333333333333,
  //     nm_end: 893.3333333333334,
  //     max_level: 60,
  //     center_gap_x: -35,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 82,
  //     gagebar_y: 25,
  //   },
  //   {
  //     name: "Hero Echo",
  //     filename: "ally_14",
  //     feature: 1,
  //     star: 6,
  //     w: 160,
  //     h: 137,
  //     move_frame_num: 4,
  //     wait_frame_num: 8,
  //     attack_frame_num: 11,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 8,
  //     fire_img_frame_num: 1,
  //     attack_fire_frame: 9,
  //     attack_len: 350,
  //     move_speed: 7,
  //     attack_speed: 30,
  //     ap_start: 2007,
  //     ap_end: 21600,
  //     hp_start: 1851,
  //     hp_end: 129600,
  //     nm_start: 813.3333333333334,
  //     nm_end: 1420,
  //     max_level: 70,
  //     center_gap_x: -34,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 82,
  //     gagebar_y: 21,
  //   },
  //   {
  //     name: "Wizard Smartie",
  //     filename: "ally_15",
  //     feature: 2,
  //     star: 2,
  //     w: 112,
  //     h: 126,
  //     move_frame_num: 10,
  //     wait_frame_num: 10,
  //     attack_frame_num: 14,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 10,
  //     fire_img_frame_num: 1,
  //     attack_fire_frame: 9,
  //     attack_len: 350,
  //     move_speed: 2,
  //     attack_speed: 40,
  //     ap_start: 18,
  //     ap_end: 72,
  //     hp_start: 17,
  //     hp_end: 520,
  //     nm_start: 60,
  //     nm_end: 210,
  //     max_level: 30,
  //     center_gap_x: 3,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 16,
  //     gagebar_y: -6,
  //   },
  //   {
  //     name: "Gentleman Smartie",
  //     filename: "ally_16",
  //     feature: 2,
  //     star: 3,
  //     w: 133,
  //     h: 156,
  //     move_frame_num: 10,
  //     wait_frame_num: 10,
  //     attack_frame_num: 14,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 10,
  //     fire_img_frame_num: 1,
  //     attack_fire_frame: 9,
  //     attack_len: 350,
  //     move_speed: 2,
  //     attack_speed: 40,
  //     ap_start: 45.6,
  //     ap_end: 216,
  //     hp_start: 39,
  //     hp_end: 1560,
  //     nm_start: 150,
  //     nm_end: 430,
  //     max_level: 40,
  //     center_gap_x: 13,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 17,
  //     gagebar_y: 21,
  //   },
  //   {
  //     name: "Frog Smartie",
  //     filename: "ally_17",
  //     feature: 2,
  //     star: 4,
  //     w: 145,
  //     h: 163,
  //     move_frame_num: 10,
  //     wait_frame_num: 10,
  //     attack_frame_num: 14,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 10,
  //     fire_img_frame_num: 1,
  //     attack_fire_frame: 9,
  //     attack_len: 350,
  //     move_speed: 1,
  //     attack_speed: 40,
  //     ap_start: 130.79999999999998,
  //     ap_end: 864,
  //     hp_start: 125,
  //     hp_end: 6240,
  //     nm_start: 350,
  //     nm_end: 800,
  //     max_level: 50,
  //     center_gap_x: 6,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 28,
  //     gagebar_y: 40,
  //   },
  //   {
  //     name: "Hip-hop Smartie",
  //     filename: "ally_18",
  //     feature: 2,
  //     star: 5,
  //     w: 140,
  //     h: 170,
  //     move_frame_num: 10,
  //     wait_frame_num: 10,
  //     attack_frame_num: 14,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 10,
  //     fire_img_frame_num: 1,
  //     attack_fire_frame: 9,
  //     attack_len: 350,
  //     move_speed: 2,
  //     attack_speed: 40,
  //     ap_start: 496.79999999999995,
  //     ap_end: 4320,
  //     hp_start: 520,
  //     hp_end: 31200,
  //     nm_start: 700,
  //     nm_end: 1360,
  //     max_level: 60,
  //     center_gap_x: 18,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 17,
  //     gagebar_y: 47,
  //   },
  //   {
  //     name: "Thor Smartie",
  //     filename: "ally_19",
  //     feature: 2,
  //     star: 6,
  //     w: 139,
  //     h: 173,
  //     move_frame_num: 10,
  //     wait_frame_num: 10,
  //     attack_frame_num: 14,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 10,
  //     fire_img_frame_num: 1,
  //     attack_fire_frame: 9,
  //     attack_len: 350,
  //     move_speed: 2,
  //     attack_speed: 40,
  //     ap_start: 2408.4,
  //     ap_end: 25920,
  //     hp_start: 2674,
  //     hp_end: 187200,
  //     nm_start: 1240,
  //     nm_end: 2150,
  //     max_level: 70,
  //     center_gap_x: 18,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 19,
  //     gagebar_y: 37,
  //   },
  //   {
  //     name: "Baseball Khan",
  //     filename: "ally_20",
  //     feature: 3,
  //     star: 2,
  //     w: 127,
  //     h: 127,
  //     move_frame_num: 12,
  //     wait_frame_num: 8,
  //     attack_frame_num: 10,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 5,
  //     fire_img_frame_num: 1,
  //     attack_fire_frame: 6,
  //     attack_len: 40,
  //     move_speed: 4,
  //     attack_speed: 30,
  //     ap_start: 13,
  //     ap_end: 50,
  //     hp_start: 72,
  //     hp_end: 2160,
  //     nm_start: 70,
  //     nm_end: 220,
  //     max_level: 30,
  //     center_gap_x: -6,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 32,
  //     gagebar_y: -1,
  //   },
  //   {
  //     name: "Boxer Khan",
  //     filename: "ally_21",
  //     feature: 3,
  //     star: 3,
  //     w: 122,
  //     h: 121,
  //     move_frame_num: 12,
  //     wait_frame_num: 8,
  //     attack_frame_num: 10,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 5,
  //     fire_img_frame_num: 1,
  //     attack_fire_frame: 6,
  //     attack_len: 40,
  //     move_speed: 4,
  //     attack_speed: 30,
  //     ap_start: 31,
  //     ap_end: 150,
  //     hp_start: 162,
  //     hp_end: 6480,
  //     nm_start: 160,
  //     nm_end: 440,
  //     max_level: 40,
  //     center_gap_x: -7,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 29,
  //     gagebar_y: 0,
  //   },
  //   {
  //     name: "Bear suit Khan",
  //     filename: "ally_22",
  //     feature: 3,
  //     star: 4,
  //     w: 135,
  //     h: 123,
  //     move_frame_num: 12,
  //     wait_frame_num: 8,
  //     attack_frame_num: 10,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 5,
  //     fire_img_frame_num: 1,
  //     attack_fire_frame: 6,
  //     attack_len: 40,
  //     move_speed: 4,
  //     attack_speed: 30,
  //     ap_start: 91,
  //     ap_end: 600,
  //     hp_start: 518.4,
  //     hp_end: 25920,
  //     nm_start: 360,
  //     nm_end: 810,
  //     max_level: 50,
  //     center_gap_x: -4,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 34,
  //     gagebar_y: -2,
  //   },
  //   {
  //     name: "Fighter Khan",
  //     filename: "ally_23",
  //     feature: 3,
  //     star: 5,
  //     w: 121,
  //     h: 121,
  //     move_frame_num: 12,
  //     wait_frame_num: 8,
  //     attack_frame_num: 10,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 5,
  //     fire_img_frame_num: 1,
  //     attack_fire_frame: 6,
  //     attack_len: 40,
  //     move_speed: 4,
  //     attack_speed: 30,
  //     ap_start: 345,
  //     ap_end: 3000,
  //     hp_start: 2160,
  //     hp_end: 129600,
  //     nm_start: 710,
  //     nm_end: 1370,
  //     max_level: 60,
  //     center_gap_x: -8,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 29,
  //     gagebar_y: -2,
  //   },
  //   {
  //     name: "Monster Khan",
  //     filename: "ally_24",
  //     feature: 3,
  //     star: 6,
  //     w: 127,
  //     h: 134,
  //     move_frame_num: 12,
  //     wait_frame_num: 8,
  //     attack_frame_num: 10,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 5,
  //     fire_img_frame_num: 1,
  //     attack_fire_frame: 6,
  //     attack_len: 40,
  //     move_speed: 4,
  //     attack_speed: 30,
  //     ap_start: 1673,
  //     ap_end: 18000,
  //     hp_start: 11107.800000000001,
  //     hp_end: 777600,
  //     nm_start: 1250,
  //     nm_end: 2160,
  //     max_level: 70,
  //     center_gap_x: -8,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 33,
  //     gagebar_y: -9,
  //   },
  //   {
  //     name: "Lucy",
  //     filename: "ally_25",
  //     feature: 4,
  //     star: 1,
  //     w: 90,
  //     h: 116,
  //     move_frame_num: 8,
  //     wait_frame_num: 8,
  //     attack_frame_num: 8,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 8,
  //     fire_img_frame_num: 1,
  //     attack_fire_frame: 6,
  //     attack_len: 200,
  //     move_speed: 2,
  //     attack_speed: 20,
  //     ap_start: 4.5,
  //     ap_end: 60,
  //     hp_start: 12,
  //     hp_end: 240,
  //     nm_start: 40,
  //     nm_end: 100,
  //     max_level: 20,
  //     center_gap_x: -1,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 10,
  //     gagebar_y: -9,
  //   },
  //   {
  //     name: "Sunglasses Lucy",
  //     filename: "ally_26",
  //     feature: 4,
  //     star: 2,
  //     w: 90,
  //     h: 116,
  //     move_frame_num: 8,
  //     wait_frame_num: 8,
  //     attack_frame_num: 8,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 8,
  //     fire_img_frame_num: 1,
  //     attack_fire_frame: 6,
  //     attack_len: 200,
  //     move_speed: 2,
  //     attack_speed: 20,
  //     ap_start: 30,
  //     ap_end: 120,
  //     hp_start: 16,
  //     hp_end: 480,
  //     nm_start: 60,
  //     nm_end: 210,
  //     max_level: 30,
  //     center_gap_x: -1,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 10,
  //     gagebar_y: -9,
  //   },
  //   {
  //     name: "Lovely Lucy",
  //     filename: "ally_27",
  //     feature: 4,
  //     star: 3,
  //     w: 143,
  //     h: 116,
  //     move_frame_num: 8,
  //     wait_frame_num: 8,
  //     attack_frame_num: 8,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 2,
  //     fire_img_frame_num: 1,
  //     attack_fire_frame: 6,
  //     attack_len: -35,
  //     move_speed: 7,
  //     attack_speed: 10,
  //     ap_start: 75,
  //     ap_end: 360,
  //     hp_start: 36,
  //     hp_end: 1440,
  //     nm_start: 150,
  //     nm_end: 430,
  //     max_level: 40,
  //     center_gap_x: 30,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 11,
  //     gagebar_y: -9,
  //   },
  //   {
  //     name: "Crown Lucy",
  //     filename: "ally_28",
  //     feature: 4,
  //     star: 4,
  //     w: 143,
  //     h: 116,
  //     move_frame_num: 8,
  //     wait_frame_num: 8,
  //     attack_frame_num: 8,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 8,
  //     fire_img_frame_num: 1,
  //     attack_fire_frame: 6,
  //     attack_len: -35,
  //     move_speed: 2,
  //     attack_speed: 20,
  //     ap_start: 217.5,
  //     ap_end: 2160,
  //     hp_start: 173,
  //     hp_end: 8640,
  //     nm_start: 350,
  //     nm_end: 800,
  //     max_level: 50,
  //     center_gap_x: 30,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 11,
  //     gagebar_y: -9,
  //   },
  //   {
  //     name: "Fighter Lucy",
  //     filename: "ally_29",
  //     feature: 4,
  //     star: 5,
  //     w: 75,
  //     h: 116,
  //     move_frame_num: 8,
  //     wait_frame_num: 8,
  //     attack_frame_num: 8,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 8,
  //     fire_img_frame_num: 1,
  //     attack_fire_frame: 6,
  //     attack_len: 200,
  //     move_speed: 2,
  //     attack_speed: 20,
  //     ap_start: 1189.5,
  //     ap_end: 8640,
  //     hp_start: 576,
  //     hp_end: 34560,
  //     nm_start: 700,
  //     nm_end: 1360,
  //     max_level: 60,
  //     center_gap_x: -8,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 8,
  //     gagebar_y: -9,
  //   },
  //   {
  //     name: "Sexy Lucy",
  //     filename: "ally_30",
  //     feature: 4,
  //     star: 6,
  //     w: 94,
  //     h: 122,
  //     move_frame_num: 8,
  //     wait_frame_num: 8,
  //     attack_frame_num: 8,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 8,
  //     fire_img_frame_num: 1,
  //     attack_fire_frame: 6,
  //     attack_len: 350,
  //     move_speed: 4,
  //     attack_speed: 20,
  //     ap_start: 4914,
  //     ap_end: 43200,
  //     hp_start: 2469,
  //     hp_end: 172800,
  //     nm_start: 1240,
  //     nm_end: 2150,
  //     max_level: 70,
  //     center_gap_x: -11,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 18,
  //     gagebar_y: -9,
  //   },
  //   {
  //     name: "Bebee",
  //     filename: "ally_31",
  //     feature: 4,
  //     star: 1,
  //     w: 92,
  //     h: 139,
  //     move_frame_num: 8,
  //     wait_frame_num: 8,
  //     attack_frame_num: 15,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 8,
  //     fire_img_frame_num: 1,
  //     attack_fire_frame: 8,
  //     attack_len: 200,
  //     move_speed: 4,
  //     attack_speed: 20,
  //     ap_start: 2,
  //     ap_end: 35,
  //     hp_start: 10,
  //     hp_end: 200,
  //     nm_start: 30,
  //     nm_end: 110,
  //     max_level: 20,
  //     center_gap_x: -15,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 22,
  //     gagebar_y: -2,
  //   },
  //   {
  //     name: "Baby Bebee",
  //     filename: "ally_32",
  //     feature: 4,
  //     star: 2,
  //     w: 115,
  //     h: 135,
  //     move_frame_num: 8,
  //     wait_frame_num: 8,
  //     attack_frame_num: 12,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 8,
  //     fire_img_frame_num: 1,
  //     attack_fire_frame: 7,
  //     attack_len: 200,
  //     move_speed: 4,
  //     attack_speed: 20,
  //     ap_start: 18,
  //     ap_end: 70,
  //     hp_start: 13,
  //     hp_end: 400,
  //     nm_start: 70,
  //     nm_end: 220,
  //     max_level: 30,
  //     center_gap_x: -10,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 26,
  //     gagebar_y: -8,
  //   },
  //   {
  //     name: "Gunman Bebee",
  //     filename: "ally_33",
  //     feature: 4,
  //     star: 3,
  //     w: 149,
  //     h: 126,
  //     move_frame_num: 8,
  //     wait_frame_num: 8,
  //     attack_frame_num: 16,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 6,
  //     fire_img_frame_num: 1,
  //     attack_fire_frame: 12,
  //     attack_len: 200,
  //     move_speed: 4,
  //     attack_speed: 20,
  //     ap_start: 44,
  //     ap_end: 210,
  //     hp_start: 30,
  //     hp_end: 1200,
  //     nm_start: 160,
  //     nm_end: 440,
  //     max_level: 40,
  //     center_gap_x: 0,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 40,
  //     gagebar_y: -13,
  //   },
  //   {
  //     name: "Bad boy Bebee",
  //     filename: "ally_34",
  //     feature: 4,
  //     star: 4,
  //     w: 134,
  //     h: 134,
  //     move_frame_num: 8,
  //     wait_frame_num: 8,
  //     attack_frame_num: 20,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 24,
  //     fire_img_frame_num: 12,
  //     attack_fire_frame: 8,
  //     attack_len: 200,
  //     move_speed: 4,
  //     attack_speed: 20,
  //     ap_start: 127,
  //     ap_end: 840,
  //     hp_start: 96,
  //     hp_end: 4800,
  //     nm_start: 360,
  //     nm_end: 810,
  //     max_level: 50,
  //     center_gap_x: -40,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 62,
  //     gagebar_y: -7,
  //   },
  //   {
  //     name: "Gladiator Bebee",
  //     filename: "ally_35",
  //     feature: 2,
  //     star: 5,
  //     w: 204,
  //     h: 168,
  //     move_frame_num: 8,
  //     wait_frame_num: 8,
  //     attack_frame_num: 9,
  //     beattack_frame_num: 5,
  //     fire_frame_num: 9,
  //     fire_img_frame_num: 9,
  //     attack_fire_frame: 3,
  //     attack_len: -35,
  //     move_speed: 4,
  //     attack_speed: 40,
  //     ap_start: 328,
  //     ap_end: 2850,
  //     hp_start: 1200,
  //     hp_end: 72000,
  //     nm_start: 710,
  //     nm_end: 1370,
  //     max_level: 60,
  //     center_gap_x: 25,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 46,
  //     gagebar_y: 29,
  //   },
  //   {
  //     name: "Ben-Hur Bebee",
  //     filename: "ally_36",
  //     feature: 2,
  //     star: 6,
  //     w: 254,
  //     h: 210,
  //     move_frame_num: 5,
  //     wait_frame_num: 8,
  //     attack_frame_num: 11,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 4,
  //     fire_img_frame_num: 1,
  //     attack_fire_frame: 10,
  //     attack_len: 90,
  //     move_speed: 2,
  //     attack_speed: 50,
  //     ap_start: 1589,
  //     ap_end: 17100,
  //     hp_start: 6171,
  //     hp_end: 432000,
  //     nm_start: 1250,
  //     nm_end: 2160,
  //     max_level: 70,
  //     center_gap_x: 0,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 46,
  //     gagebar_y: -12,
  //   },
  //   {
  //     name: "Ruby",
  //     filename: "ally_37",
  //     feature: 2,
  //     star: 1,
  //     w: 81,
  //     h: 115,
  //     move_frame_num: 7,
  //     wait_frame_num: 8,
  //     attack_frame_num: 8,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 10,
  //     fire_img_frame_num: 1,
  //     attack_fire_frame: 6,
  //     attack_len: 180,
  //     move_speed: 4,
  //     attack_speed: 50,
  //     ap_start: 3,
  //     ap_end: 30,
  //     hp_start: 13,
  //     hp_end: 260,
  //     nm_start: 40,
  //     nm_end: 100,
  //     max_level: 20,
  //     center_gap_x: -20,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 20,
  //     gagebar_y: -9,
  //   },
  //   {
  //     name: "Indian Ruby",
  //     filename: "ally_38",
  //     feature: 2,
  //     star: 2,
  //     w: 96,
  //     h: 116,
  //     move_frame_num: 8,
  //     wait_frame_num: 8,
  //     attack_frame_num: 9,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 10,
  //     fire_img_frame_num: 5,
  //     attack_fire_frame: 8,
  //     attack_len: 400,
  //     move_speed: 4,
  //     attack_speed: 30,
  //     ap_start: 15,
  //     ap_end: 60,
  //     hp_start: 17,
  //     hp_end: 520,
  //     nm_start: 60,
  //     nm_end: 210,
  //     max_level: 30,
  //     center_gap_x: -10,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 20,
  //     gagebar_y: -8,
  //   },
  //   {
  //     name: "Cupid Ruby",
  //     filename: "ally_39",
  //     feature: 2,
  //     star: 3,
  //     w: 116,
  //     h: 139,
  //     move_frame_num: 6,
  //     wait_frame_num: 8,
  //     attack_frame_num: 9,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 17,
  //     fire_img_frame_num: 10,
  //     attack_fire_frame: 8,
  //     attack_len: 400,
  //     move_speed: 4,
  //     attack_speed: 30,
  //     ap_start: 38,
  //     ap_end: 180,
  //     hp_start: 39,
  //     hp_end: 1560,
  //     nm_start: 150,
  //     nm_end: 430,
  //     max_level: 40,
  //     center_gap_x: -15,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 35,
  //     gagebar_y: -9,
  //   },
  //   {
  //     name: "Mask Ruby",
  //     filename: "ally_40",
  //     feature: 2,
  //     star: 4,
  //     w: 126,
  //     h: 119,
  //     move_frame_num: 8,
  //     wait_frame_num: 8,
  //     attack_frame_num: 9,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 36,
  //     fire_img_frame_num: 12,
  //     attack_fire_frame: 8,
  //     attack_len: 840,
  //     move_speed: 4,
  //     attack_speed: 100,
  //     ap_start: 109,
  //     ap_end: 720,
  //     hp_start: 125,
  //     hp_end: 6240,
  //     nm_start: 350,
  //     nm_end: 800,
  //     max_level: 50,
  //     center_gap_x: -40,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 53,
  //     gagebar_y: -13,
  //   },
  //   {
  //     name: "Red Manteau Ruby",
  //     filename: "ally_41",
  //     feature: 2,
  //     star: 5,
  //     w: 123,
  //     h: 150,
  //     move_frame_num: 8,
  //     wait_frame_num: 8,
  //     attack_frame_num: 14,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 7,
  //     fire_img_frame_num: 1,
  //     attack_fire_frame: 12,
  //     attack_len: 700,
  //     move_speed: 4,
  //     attack_speed: 30,
  //     ap_start: 414,
  //     ap_end: 3600,
  //     hp_start: 520,
  //     hp_end: 31200,
  //     nm_start: 700,
  //     nm_end: 1360,
  //     max_level: 60,
  //     center_gap_x: -15,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 33,
  //     gagebar_y: 20,
  //   },
  //   {
  //     name: "Queen Ruby",
  //     filename: "ally_42",
  //     feature: 2,
  //     star: 6,
  //     w: 265,
  //     h: 254,
  //     move_frame_num: 12,
  //     wait_frame_num: 8,
  //     attack_frame_num: 10,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 19,
  //     fire_img_frame_num: 1,
  //     attack_fire_frame: 6,
  //     attack_len: 720,
  //     move_speed: 4,
  //     attack_speed: 30,
  //     ap_start: 2007,
  //     ap_end: 21600,
  //     hp_start: 2674,
  //     hp_end: 350000,
  //     nm_start: 1240,
  //     nm_end: 2150,
  //     max_level: 70,
  //     center_gap_x: 28,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 81,
  //     gagebar_y: -8,
  //   },
  //   {
  //     name: "Mummy Goldman",
  //     filename: "ally_43",
  //     feature: 4,
  //     star: 2,
  //     w: 202,
  //     h: 176,
  //     move_frame_num: 11,
  //     wait_frame_num: 10,
  //     attack_frame_num: 11,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 6,
  //     fire_img_frame_num: 0,
  //     attack_fire_frame: 6,
  //     attack_len: -35,
  //     move_speed: 2,
  //     attack_speed: 30,
  //     ap_start: 18,
  //     ap_end: 70,
  //     hp_start: 13,
  //     hp_end: 400,
  //     nm_start: 70,
  //     nm_end: 220,
  //     max_level: 30,
  //     center_gap_x: 20,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 50,
  //     gagebar_y: 15,
  //   },
  //   {
  //     name: "Bandage Goldman",
  //     filename: "ally_44",
  //     feature: 4,
  //     star: 3,
  //     w: 196,
  //     h: 162,
  //     move_frame_num: 11,
  //     wait_frame_num: 10,
  //     attack_frame_num: 12,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 6,
  //     fire_img_frame_num: 0,
  //     attack_fire_frame: 9,
  //     attack_len: -35,
  //     move_speed: 2,
  //     attack_speed: 30,
  //     ap_start: 44,
  //     ap_end: 210,
  //     hp_start: 30,
  //     hp_end: 1200,
  //     nm_start: 160,
  //     nm_end: 440,
  //     max_level: 40,
  //     center_gap_x: 20,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 50,
  //     gagebar_y: 5,
  //   },
  //   {
  //     name: "Mask Goldman",
  //     filename: "ally_45",
  //     feature: 4,
  //     star: 4,
  //     w: 254,
  //     h: 187,
  //     move_frame_num: 12,
  //     wait_frame_num: 10,
  //     attack_frame_num: 14,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 6,
  //     fire_img_frame_num: 0,
  //     attack_fire_frame: 11,
  //     attack_len: -35,
  //     move_speed: 4,
  //     attack_speed: 30,
  //     ap_start: 127,
  //     ap_end: 840,
  //     hp_start: 96,
  //     hp_end: 4800,
  //     nm_start: 360,
  //     nm_end: 810,
  //     max_level: 50,
  //     center_gap_x: 30,
  //     center_gap_y: 0,
  //     beattack_margine: -90,
  //     gagebar_x: 66,
  //     gagebar_y: 30,
  //   },
  //   {
  //     name: "Warrior Goldman",
  //     filename: "ally_46",
  //     feature: 4,
  //     star: 5,
  //     w: 254,
  //     h: 187,
  //     move_frame_num: 12,
  //     wait_frame_num: 10,
  //     attack_frame_num: 12,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 6,
  //     fire_img_frame_num: 0,
  //     attack_fire_frame: 9,
  //     attack_len: -35,
  //     move_speed: 6,
  //     attack_speed: 10,
  //     ap_start: 600,
  //     ap_end: 3500,
  //     hp_start: 600,
  //     hp_end: 24000,
  //     nm_start: 710,
  //     nm_end: 1370,
  //     max_level: 60,
  //     center_gap_x: 30,
  //     center_gap_y: 0,
  //     beattack_margine: -20,
  //     gagebar_x: 70,
  //     gagebar_y: 35,
  //   },
  //   {
  //     name: "Gladiator Goldman",
  //     filename: "ally_47",
  //     feature: 2,
  //     star: 6,
  //     w: 296,
  //     h: 242,
  //     move_frame_num: 12,
  //     wait_frame_num: 10,
  //     attack_frame_num: 12,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 18,
  //     fire_img_frame_num: 3,
  //     attack_fire_frame: 8,
  //     attack_len: 525,
  //     move_speed: 4,
  //     attack_speed: 20,
  //     ap_start: 2000,
  //     ap_end: 20000,
  //     hp_start: 2057,
  //     hp_end: 124000,
  //     nm_start: 1250,
  //     nm_end: 2160,
  //     max_level: 70,
  //     center_gap_x: 12,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 90,
  //     gagebar_y: 35,
  //   },
  //   {
  //     name: "Legend Goldman",
  //     filename: "ally_48",
  //     feature: 2,
  //     star: 7,
  //     w: 311,
  //     h: 299,
  //     move_frame_num: 10,
  //     wait_frame_num: 10,
  //     attack_frame_num: 12,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 6,
  //     fire_img_frame_num: 6,
  //     attack_fire_frame: 7,
  //     attack_len: 525,
  //     move_speed: 1,
  //     attack_speed: 60,
  //     ap_start: 10000,
  //     ap_end: 200000,
  //     hp_start: 10000,
  //     hp_end: 450000,
  //     nm_start: 2700,
  //     nm_end: 4000,
  //     max_level: 80,
  //     center_gap_x: -6,
  //     center_gap_y: -3,
  //     beattack_margine: 0,
  //     gagebar_x: 130,
  //     gagebar_y: 35,
  //   },
  //   {
  //     name: "Archangel Lucy",
  //     filename: "ally_49",
  //     feature: 2,
  //     star: 7,
  //     w: 384,
  //     h: 331,
  //     move_frame_num: 5,
  //     wait_frame_num: 5,
  //     attack_frame_num: 9,
  //     beattack_frame_num: 4,
  //     fire_frame_num: 6,
  //     fire_img_frame_num: 6,
  //     attack_fire_frame: 6,
  //     attack_len: 700,
  //     move_speed: 6,
  //     attack_speed: 30,
  //     ap_start: 8000,
  //     ap_end: 50000,
  //     hp_start: 10000,
  //     hp_end: 380000,
  //     nm_start: 1900,
  //     nm_end: 6000,
  //     max_level: 80,
  //     center_gap_x: 8,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 150,
  //     gagebar_y: 116,
  //   },
  //   {
  //     name: "SSister Lucy",
  //     filename: "ally_50",
  //     feature: 2,
  //     star: 7,
  //     w: 460,
  //     h: 277,
  //     move_frame_num: 4,
  //     wait_frame_num: 4,
  //     attack_frame_num: 9,
  //     beattack_frame_num: 4,
  //     fire_frame_num: 5,
  //     fire_img_frame_num: 1,
  //     attack_fire_frame: 6,
  //     attack_len: 90,
  //     move_speed: 14,
  //     attack_speed: 10,
  //     ap_start: 11000,
  //     ap_end: 210000,
  //     hp_start: 50000,
  //     hp_end: 550000,
  //     nm_start: 2000,
  //     nm_end: 5000,
  //     max_level: 80,
  //     center_gap_x: 15,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 121,
  //     gagebar_y: 77,
  //   },
  //   {
  //     name: "Gingerman",
  //     filename: "ally_51",
  //     feature: 4,
  //     star: 2,
  //     w: 165,
  //     h: 160,
  //     move_frame_num: 6,
  //     wait_frame_num: 5,
  //     attack_frame_num: 7,
  //     beattack_frame_num: 4,
  //     fire_frame_num: 6,
  //     fire_img_frame_num: 0,
  //     attack_fire_frame: 5,
  //     attack_len: -35,
  //     move_speed: 6,
  //     attack_speed: 30,
  //     ap_start: 23,
  //     ap_end: 91,
  //     hp_start: 16,
  //     hp_end: 480,
  //     nm_start: 84,
  //     nm_end: 264,
  //     max_level: 30,
  //     center_gap_x: 16,
  //     center_gap_y: 0,
  //     beattack_margine: 20,
  //     gagebar_x: 46,
  //     gagebar_y: 33,
  //   },
  //   {
  //     name: "Candy Gingerman",
  //     filename: "ally_52",
  //     feature: 4,
  //     star: 3,
  //     w: 219,
  //     h: 153,
  //     move_frame_num: 6,
  //     wait_frame_num: 5,
  //     attack_frame_num: 7,
  //     beattack_frame_num: 4,
  //     fire_frame_num: 6,
  //     fire_img_frame_num: 0,
  //     attack_fire_frame: 4,
  //     attack_len: -35,
  //     move_speed: 6,
  //     attack_speed: 20,
  //     ap_start: 57,
  //     ap_end: 273,
  //     hp_start: 36,
  //     hp_end: 1440,
  //     nm_start: 192,
  //     nm_end: 528,
  //     max_level: 40,
  //     center_gap_x: 28,
  //     center_gap_y: 0,
  //     beattack_margine: -80,
  //     gagebar_x: 57,
  //     gagebar_y: 25,
  //   },
  //   {
  //     name: "Cream Gingerman",
  //     filename: "ally_53",
  //     feature: 4,
  //     star: 4,
  //     w: 224,
  //     h: 156,
  //     move_frame_num: 6,
  //     wait_frame_num: 5,
  //     attack_frame_num: 7,
  //     beattack_frame_num: 4,
  //     fire_frame_num: 5,
  //     fire_img_frame_num: 4,
  //     attack_fire_frame: 5,
  //     attack_len: 200,
  //     move_speed: 6,
  //     attack_speed: 20,
  //     ap_start: 165,
  //     ap_end: 1092,
  //     hp_start: 115,
  //     hp_end: 5760,
  //     nm_start: 460,
  //     nm_end: 910,
  //     max_level: 50,
  //     center_gap_x: 36,
  //     center_gap_y: 0,
  //     beattack_margine: 20,
  //     gagebar_x: 55,
  //     gagebar_y: 15,
  //   },
  //   {
  //     name: "Ninja Gingerman",
  //     filename: "ally_54",
  //     feature: 1,
  //     star: 5,
  //     w: 140,
  //     h: 275,
  //     move_frame_num: 6,
  //     wait_frame_num: 5,
  //     attack_frame_num: 10,
  //     beattack_frame_num: 4,
  //     fire_frame_num: 7,
  //     fire_img_frame_num: 7,
  //     attack_fire_frame: 4,
  //     attack_len: 200,
  //     move_speed: 7,
  //     attack_speed: 10,
  //     ap_start: 600,
  //     ap_end: 4550,
  //     hp_start: 600,
  //     hp_end: 28800,
  //     nm_start: 810,
  //     nm_end: 1470,
  //     max_level: 60,
  //     center_gap_x: 0,
  //     center_gap_y: 0,
  //     beattack_margine: 20,
  //     gagebar_x: 42,
  //     gagebar_y: 140,
  //   },
  //   {
  //     name: "Black Gingerman",
  //     filename: "ally_55",
  //     feature: 2,
  //     star: 6,
  //     w: 224,
  //     h: 160,
  //     move_frame_num: 6,
  //     wait_frame_num: 5,
  //     attack_frame_num: 8,
  //     beattack_frame_num: 4,
  //     fire_frame_num: 8,
  //     fire_img_frame_num: 3,
  //     attack_fire_frame: 5,
  //     attack_len: 455,
  //     move_speed: 6,
  //     attack_speed: 20,
  //     ap_start: 2100,
  //     ap_end: 26000,
  //     hp_start: 2100,
  //     hp_end: 148800,
  //     nm_start: 1240,
  //     nm_end: 2150,
  //     max_level: 70,
  //     center_gap_x: 16,
  //     center_gap_y: 0,
  //     beattack_margine: -50,
  //     gagebar_x: 62,
  //     gagebar_y: 14,
  //   },
  //   {
  //     name: "Devil Gingerman",
  //     filename: "ally_56",
  //     feature: 2,
  //     star: 7,
  //     w: 308,
  //     h: 241,
  //     move_frame_num: 6,
  //     wait_frame_num: 5,
  //     attack_frame_num: 10,
  //     beattack_frame_num: 4,
  //     fire_frame_num: 12,
  //     fire_img_frame_num: 15,
  //     attack_fire_frame: 7,
  //     attack_len: 630,
  //     move_speed: 6,
  //     attack_speed: 30,
  //     ap_start: 2000,
  //     ap_end: 180000,
  //     hp_start: 15000,
  //     hp_end: 450000,
  //     nm_start: 3200,
  //     nm_end: 5000,
  //     max_level: 80,
  //     center_gap_x: 37,
  //     center_gap_y: 0,
  //     beattack_margine: -50,
  //     gagebar_x: 96,
  //     gagebar_y: 60,
  //   },
  //   {
  //     name: "Bensi",
  //     filename: "ally_57",
  //     feature: 4,
  //     star: 2,
  //     w: 117,
  //     h: 151,
  //     move_frame_num: 8,
  //     wait_frame_num: 8,
  //     attack_frame_num: 10,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 10,
  //     fire_img_frame_num: 1,
  //     attack_fire_frame: 8,
  //     attack_len: 350,
  //     move_speed: 2,
  //     attack_speed: 20,
  //     ap_start: 23,
  //     ap_end: 91,
  //     hp_start: 16,
  //     hp_end: 480,
  //     nm_start: 84,
  //     nm_end: 264,
  //     max_level: 30,
  //     center_gap_x: 16,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 17,
  //     gagebar_y: -11,
  //   },
  //   {
  //     name: "Heart girl Bensi",
  //     filename: "ally_58",
  //     feature: 4,
  //     star: 3,
  //     w: 130,
  //     h: 151,
  //     move_frame_num: 8,
  //     wait_frame_num: 8,
  //     attack_frame_num: 8,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 10,
  //     fire_img_frame_num: 1,
  //     attack_fire_frame: 6,
  //     attack_len: 350,
  //     move_speed: 2,
  //     attack_speed: 20,
  //     ap_start: 57,
  //     ap_end: 273,
  //     hp_start: 36,
  //     hp_end: 1440,
  //     nm_start: 192,
  //     nm_end: 528,
  //     max_level: 40,
  //     center_gap_x: 28,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 17,
  //     gagebar_y: -11,
  //   },
  //   {
  //     name: "Cheer leader Bensi",
  //     filename: "ally_59",
  //     feature: 4,
  //     star: 4,
  //     w: 117,
  //     h: 151,
  //     move_frame_num: 8,
  //     wait_frame_num: 8,
  //     attack_frame_num: 16,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 6,
  //     fire_img_frame_num: 6,
  //     attack_fire_frame: 11,
  //     attack_len: 350,
  //     move_speed: 2,
  //     attack_speed: 20,
  //     ap_start: 165,
  //     ap_end: 1092,
  //     hp_start: 115,
  //     hp_end: 5760,
  //     nm_start: 460,
  //     nm_end: 910,
  //     max_level: 50,
  //     center_gap_x: 10,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 17,
  //     gagebar_y: -11,
  //   },
  //   {
  //     name: "Witch Bensi",
  //     filename: "ally_60",
  //     feature: 4,
  //     star: 5,
  //     w: 152,
  //     h: 147,
  //     move_frame_num: 8,
  //     wait_frame_num: 8,
  //     attack_frame_num: 11,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 12,
  //     fire_img_frame_num: 12,
  //     attack_fire_frame: 5,
  //     attack_len: 350,
  //     move_speed: 2,
  //     attack_speed: 20,
  //     ap_start: 600,
  //     ap_end: 4550,
  //     hp_start: 600,
  //     hp_end: 28800,
  //     nm_start: 810,
  //     nm_end: 1470,
  //     max_level: 60,
  //     center_gap_x: 0,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 49,
  //     gagebar_y: -9,
  //   },
  //   {
  //     name: "Magician Bensi",
  //     filename: "ally_61",
  //     feature: 4,
  //     star: 6,
  //     w: 248,
  //     h: 296,
  //     move_frame_num: 8,
  //     wait_frame_num: 8,
  //     attack_frame_num: 10,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 10,
  //     fire_img_frame_num: 10,
  //     attack_fire_frame: 4,
  //     attack_len: 350,
  //     move_speed: 2,
  //     attack_speed: 20,
  //     ap_start: 2100,
  //     ap_end: 26000,
  //     hp_start: 2100,
  //     hp_end: 148800,
  //     nm_start: 1240,
  //     nm_end: 2150,
  //     max_level: 70,
  //     center_gap_x: -20,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 102,
  //     gagebar_y: 136,
  //   },
  //   {
  //     name: "Angel Bensi",
  //     filename: "ally_62",
  //     feature: 2,
  //     star: 7,
  //     w: 300,
  //     h: 300,
  //     move_frame_num: 8,
  //     wait_frame_num: 8,
  //     attack_frame_num: 16,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 9,
  //     fire_img_frame_num: 9,
  //     attack_fire_frame: 8,
  //     attack_len: 350,
  //     move_speed: 2,
  //     attack_speed: 20,
  //     ap_start: 2000,
  //     ap_end: 180000,
  //     hp_start: 15000,
  //     hp_end: 450000,
  //     nm_start: 3200,
  //     nm_end: 5000,
  //     max_level: 80,
  //     center_gap_x: 37,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 79,
  //     gagebar_y: 144,
  //   },
  //   {
  //     name: "Viking Ace",
  //     filename: "ally_63",
  //     feature: 4,
  //     star: 7,
  //     w: 315,
  //     h: 298,
  //     move_frame_num: 13,
  //     wait_frame_num: 10,
  //     attack_frame_num: 15,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 13,
  //     fire_img_frame_num: 14,
  //     attack_fire_frame: 2,
  //     attack_len: 350,
  //     move_speed: 4,
  //     attack_speed: 20,
  //     ap_start: 8000,
  //     ap_end: 400000,
  //     hp_start: 25000,
  //     hp_end: 500000,
  //     nm_start: 3000,
  //     nm_end: 5000,
  //     max_level: 80,
  //     center_gap_x: 0,
  //     center_gap_y: 0,
  //     beattack_margine: -70,
  //     gagebar_x: 207,
  //     gagebar_y: 65,
  //   },
  //   {
  //     name: "Black Bebee",
  //     filename: "ally_64",
  //     feature: 2,
  //     star: 7,
  //     w: 274,
  //     h: 212,
  //     move_frame_num: 4,
  //     wait_frame_num: 8,
  //     attack_frame_num: 12,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 4,
  //     fire_img_frame_num: 1,
  //     attack_fire_frame: 6,
  //     attack_len: 200,
  //     move_speed: 2,
  //     attack_speed: 50,
  //     ap_start: 8000,
  //     ap_end: 120000,
  //     hp_start: 8000,
  //     hp_end: 330000,
  //     nm_start: 1900,
  //     nm_end: 6000,
  //     max_level: 80,
  //     center_gap_x: 0,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 46,
  //     gagebar_y: -12,
  //   },
  //   {
  //     name: "Venus Ruby",
  //     filename: "ally_65",
  //     feature: 2,
  //     star: 7,
  //     w: 249,
  //     h: 259,
  //     move_frame_num: 12,
  //     wait_frame_num: 8,
  //     attack_frame_num: 10,
  //     beattack_frame_num: 6,
  //     fire_frame_num: 15,
  //     fire_img_frame_num: 1,
  //     attack_fire_frame: 6,
  //     attack_len: 720,
  //     move_speed: 4,
  //     attack_speed: 30,
  //     ap_start: 8000,
  //     ap_end: 250000,
  //     hp_start: 20000,
  //     hp_end: 450000,
  //     nm_start: 3000,
  //     nm_end: 5000,
  //     max_level: 80,
  //     center_gap_x: 0,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 81,
  //     gagebar_y: -8,
  //   },
  //   {
  //     name: "Prime Echo",
  //     filename: "ally_66",
  //     feature: 1,
  //     star: 7,
  //     w: 226,
  //     h: 268,
  //     move_frame_num: 10,
  //     wait_frame_num: 10,
  //     attack_frame_num: 10,
  //     beattack_frame_num: 8,
  //     fire_frame_num: 8,
  //     fire_img_frame_num: 8,
  //     attack_fire_frame: 9,
  //     attack_len: -35,
  //     move_speed: 7,
  //     attack_speed: 10,
  //     ap_start: 7000,
  //     ap_end: 250000,
  //     hp_start: 22000,
  //     hp_end: 400000,
  //     nm_start: 1900,
  //     nm_end: 6000,
  //     max_level: 80,
  //     center_gap_x: -45,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 120,
  //     gagebar_y: 50,
  //   },
  //   {
  //     name: "Guardian Smartie",
  //     filename: "ally_67",
  //     feature: 2,
  //     star: 7,
  //     w: 198,
  //     h: 230,
  //     move_frame_num: 6,
  //     wait_frame_num: 8,
  //     attack_frame_num: 12,
  //     beattack_frame_num: 8,
  //     fire_frame_num: 14,
  //     fire_img_frame_num: 14,
  //     attack_fire_frame: 11,
  //     attack_len: 700,
  //     move_speed: 2,
  //     attack_speed: 40,
  //     ap_start: 6000,
  //     ap_end: 160000,
  //     hp_start: 7000,
  //     hp_end: 350000,
  //     nm_start: 2000,
  //     nm_end: 6000,
  //     max_level: 80,
  //     center_gap_x: 0,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 60,
  //     gagebar_y: 30,
  //   },
  //   {
  //     name: "Iron Khan",
  //     filename: "ally_68",
  //     feature: 3,
  //     star: 7,
  //     w: 254,
  //     h: 189,
  //     move_frame_num: 6,
  //     wait_frame_num: 5,
  //     attack_frame_num: 6,
  //     beattack_frame_num: 8,
  //     fire_frame_num: 6,
  //     fire_img_frame_num: 1,
  //     attack_fire_frame: 6,
  //     attack_len: -35,
  //     move_speed: 4,
  //     attack_speed: 30,
  //     ap_start: 1,
  //     ap_end: 1,
  //     hp_start: 100000,
  //     hp_end: 7776000,
  //     nm_start: 4500,
  //     nm_end: 9000,
  //     max_level: 80,
  //     center_gap_x: -20,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 100,
  //     gagebar_y: 0,
  //   },
  //   {
  //     name: "Jey",
  //     filename: "ally_69",
  //     feature: 1,
  //     star: 1,
  //     w: 132,
  //     h: 139,
  //     move_frame_num: 4,
  //     wait_frame_num: 6,
  //     attack_frame_num: 8,
  //     beattack_frame_num: 4,
  //     fire_frame_num: 10,
  //     fire_img_frame_num: 5,
  //     attack_fire_frame: 6,
  //     attack_len: 200,
  //     move_speed: 7,
  //     attack_speed: 30,
  //     ap_start: 1,
  //     ap_end: 25,
  //     hp_start: 10,
  //     hp_end: 150,
  //     nm_start: 20,
  //     nm_end: 80,
  //     max_level: 20,
  //     center_gap_x: 0,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 36,
  //     gagebar_y: -8,
  //   },
  //   {
  //     name: "Cheddar Jey",
  //     filename: "ally_70",
  //     feature: 1,
  //     star: 2,
  //     w: 125,
  //     h: 139,
  //     move_frame_num: 4,
  //     wait_frame_num: 6,
  //     attack_frame_num: 8,
  //     beattack_frame_num: 4,
  //     fire_frame_num: 14,
  //     fire_img_frame_num: 7,
  //     attack_fire_frame: 6,
  //     attack_len: 200,
  //     move_speed: 7,
  //     attack_speed: 30,
  //     ap_start: 10,
  //     ap_end: 50,
  //     hp_start: 12,
  //     hp_end: 300,
  //     nm_start: 40,
  //     nm_end: 190,
  //     max_level: 30,
  //     center_gap_x: -10,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 30,
  //     gagebar_y: -8,
  //   },
  //   {
  //     name: "Thief Jey",
  //     filename: "ally_71",
  //     feature: 1,
  //     star: 3,
  //     w: 143,
  //     h: 145,
  //     move_frame_num: 4,
  //     wait_frame_num: 6,
  //     attack_frame_num: 8,
  //     beattack_frame_num: 4,
  //     fire_frame_num: 5,
  //     fire_img_frame_num: 5,
  //     attack_fire_frame: 6,
  //     attack_len: 200,
  //     move_speed: 7,
  //     attack_speed: 30,
  //     ap_start: 25,
  //     ap_end: 140,
  //     hp_start: 27,
  //     hp_end: 950,
  //     nm_start: 130,
  //     nm_end: 410,
  //     max_level: 40,
  //     center_gap_x: -10,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 40,
  //     gagebar_y: -8,
  //   },
  //   {
  //     name: "Robbin Hood Jey",
  //     filename: "ally_72",
  //     feature: 1,
  //     star: 4,
  //     w: 148,
  //     h: 146,
  //     move_frame_num: 4,
  //     wait_frame_num: 6,
  //     attack_frame_num: 9,
  //     beattack_frame_num: 4,
  //     fire_frame_num: 5,
  //     fire_img_frame_num: 5,
  //     attack_fire_frame: 8,
  //     attack_len: 200,
  //     move_speed: 7,
  //     attack_speed: 30,
  //     ap_start: 73,
  //     ap_end: 600,
  //     hp_start: 86,
  //     hp_end: 3900,
  //     nm_start: 330,
  //     nm_end: 780,
  //     max_level: 50,
  //     center_gap_x: 0,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 43,
  //     gagebar_y: -8,
  //   },
  //   {
  //     name: "General Jey",
  //     filename: "ally_73",
  //     feature: 4,
  //     star: 5,
  //     w: 241,
  //     h: 191,
  //     move_frame_num: 4,
  //     wait_frame_num: 6,
  //     attack_frame_num: 14,
  //     beattack_frame_num: 4,
  //     fire_frame_num: 5,
  //     fire_img_frame_num: 5,
  //     attack_fire_frame: 12,
  //     attack_len: 420,
  //     move_speed: 6,
  //     attack_speed: 30,
  //     ap_start: 328,
  //     ap_end: 2850,
  //     hp_start: 1200,
  //     hp_end: 72000,
  //     nm_start: 710,
  //     nm_end: 1370,
  //     max_level: 60,
  //     center_gap_x: 20,
  //     center_gap_y: 0,
  //     beattack_margine: -70,
  //     gagebar_x: 73,
  //     gagebar_y: 21,
  //   },
  //   {
  //     name: "Cannon Jey",
  //     filename: "ally_74",
  //     feature: 2,
  //     star: 6,
  //     w: 271,
  //     h: 167,
  //     move_frame_num: 4,
  //     wait_frame_num: 6,
  //     attack_frame_num: 12,
  //     beattack_frame_num: 4,
  //     fire_frame_num: 8,
  //     fire_img_frame_num: 4,
  //     attack_fire_frame: 6,
  //     attack_len: 525,
  //     move_speed: 2,
  //     attack_speed: 40,
  //     ap_start: 2007,
  //     ap_end: 25000,
  //     hp_start: 2674,
  //     hp_end: 250000,
  //     nm_start: 1240,
  //     nm_end: 2150,
  //     max_level: 70,
  //     center_gap_x: 0,
  //     center_gap_y: 0,
  //     beattack_margine: -100,
  //     gagebar_x: 80,
  //     gagebar_y: 1,
  //   },
  //   {
  //     name: "Soulful Jey",
  //     filename: "ally_75",
  //     feature: 2,
  //     star: 7,
  //     w: 259,
  //     h: 234,
  //     move_frame_num: 8,
  //     wait_frame_num: 6,
  //     attack_frame_num: 15,
  //     beattack_frame_num: 4,
  //     fire_frame_num: 12,
  //     fire_img_frame_num: 6,
  //     attack_fire_frame: 11,
  //     attack_len: 630,
  //     move_speed: 6,
  //     attack_speed: 40,
  //     ap_start: 6000,
  //     ap_end: 180000,
  //     hp_start: 7000,
  //     hp_end: 380000,
  //     nm_start: 4950,
  //     nm_end: 9900,
  //     max_level: 80,
  //     center_gap_x: 30,
  //     center_gap_y: 0,
  //     beattack_margine: -100,
  //     gagebar_x: 76,
  //     gagebar_y: 0,
  //   },
  //   {
  //     name: "Koo",
  //     filename: "ally_76",
  //     feature: 1,
  //     star: 2,
  //     w: 173,
  //     h: 157,
  //     move_frame_num: 5,
  //     wait_frame_num: 6,
  //     attack_frame_num: 9,
  //     beattack_frame_num: 1,
  //     fire_frame_num: 5,
  //     fire_img_frame_num: 1,
  //     attack_fire_frame: 4,
  //     attack_len: -200,
  //     move_speed: 6,
  //     attack_speed: 30,
  //     ap_start: 12,
  //     ap_end: 45,
  //     hp_start: 1,
  //     hp_end: 1,
  //     nm_start: 84,
  //     nm_end: 264,
  //     max_level: 30,
  //     center_gap_x: 0,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 56,
  //     gagebar_y: 48,
  //   },
  //   {
  //     name: "Gold Koo",
  //     filename: "ally_77",
  //     feature: 1,
  //     star: 3,
  //     w: 159,
  //     h: 170,
  //     move_frame_num: 6,
  //     wait_frame_num: 6,
  //     attack_frame_num: 8,
  //     beattack_frame_num: 1,
  //     fire_frame_num: 5,
  //     fire_img_frame_num: 1,
  //     attack_fire_frame: 3,
  //     attack_len: -200,
  //     move_speed: 6,
  //     attack_speed: 30,
  //     ap_start: 27,
  //     ap_end: 135,
  //     hp_start: 1,
  //     hp_end: 1,
  //     nm_start: 192,
  //     nm_end: 528,
  //     max_level: 40,
  //     center_gap_x: -20,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 48,
  //     gagebar_y: 32,
  //   },
  //   {
  //     name: "Cutedoll Koo",
  //     filename: "ally_78",
  //     feature: 1,
  //     star: 4,
  //     w: 229,
  //     h: 195,
  //     move_frame_num: 5,
  //     wait_frame_num: 6,
  //     attack_frame_num: 9,
  //     beattack_frame_num: 1,
  //     fire_frame_num: 5,
  //     fire_img_frame_num: 1,
  //     attack_fire_frame: 4,
  //     attack_len: -200,
  //     move_speed: 6,
  //     attack_speed: 30,
  //     ap_start: 83,
  //     ap_end: 545,
  //     hp_start: 1,
  //     hp_end: 1,
  //     nm_start: 460,
  //     nm_end: 910,
  //     max_level: 50,
  //     center_gap_x: 25,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 48,
  //     gagebar_y: 46,
  //   },
  //   {
  //     name: "Cowboy Koo",
  //     filename: "ally_79",
  //     feature: 1,
  //     star: 5,
  //     w: 381,
  //     h: 261,
  //     move_frame_num: 7,
  //     wait_frame_num: 6,
  //     attack_frame_num: 7,
  //     beattack_frame_num: 1,
  //     fire_frame_num: 5,
  //     fire_img_frame_num: 1,
  //     attack_fire_frame: 2,
  //     attack_len: -380,
  //     move_speed: 6,
  //     attack_speed: 30,
  //     ap_start: 300,
  //     ap_end: 2250,
  //     hp_start: 1,
  //     hp_end: 1,
  //     nm_start: 810,
  //     nm_end: 1470,
  //     max_level: 60,
  //     center_gap_x: 150,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 38,
  //     gagebar_y: 81,
  //   },
  //   {
  //     name: "Vacance Koo",
  //     filename: "ally_80",
  //     feature: 1,
  //     star: 6,
  //     w: 361,
  //     h: 292,
  //     move_frame_num: 9,
  //     wait_frame_num: 6,
  //     attack_frame_num: 8,
  //     beattack_frame_num: 1,
  //     fire_frame_num: 5,
  //     fire_img_frame_num: 1,
  //     attack_fire_frame: 3,
  //     attack_len: -380,
  //     move_speed: 6,
  //     attack_speed: 30,
  //     ap_start: 1000,
  //     ap_end: 13000,
  //     hp_start: 1,
  //     hp_end: 1,
  //     nm_start: 3200,
  //     nm_end: 5000,
  //     max_level: 70,
  //     center_gap_x: 80,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 70,
  //     gagebar_y: 67,
  //   },
  //   {
  //     name: "Disco Koo",
  //     filename: "ally_81",
  //     feature: 1,
  //     star: 7,
  //     w: 325,
  //     h: 271,
  //     move_frame_num: 9,
  //     wait_frame_num: 6,
  //     attack_frame_num: 8,
  //     beattack_frame_num: 1,
  //     fire_frame_num: 5,
  //     fire_img_frame_num: 1,
  //     attack_fire_frame: 3,
  //     attack_len: -280,
  //     move_speed: 6,
  //     attack_speed: 30,
  //     ap_start: 1100,
  //     ap_end: 90000,
  //     hp_start: 1,
  //     hp_end: 1,
  //     nm_start: 4950,
  //     nm_end: 9900,
  //     max_level: 80,
  //     center_gap_x: 50,
  //     center_gap_y: 0,
  //     beattack_margine: 0,
  //     gagebar_x: 69,
  //     gagebar_y: 88,
  //   },
  // ];

  // export const itemList = [
  //   {
  //     name: -1,
  //     filename: -1,
  //     grade: -1,
  //     type: -1,
  //     base_option: -1,
  //     base_option_num: -1,
  //     temp: "",
  //   },

  //   {
  //     name: "시계 문양",
  //     filename: "f_casque",
  //     grade: "f",
  //     type: "casque",
  //     base_option: "PS",
  //     base_option_num: 10,
  //     temp: "",
  //   },
  //   {
  //     name: "시계 문양",
  //     filename: "f_casque",
  //     grade: "f",
  //     type: "casque",
  //     base_option: "PS",
  //     base_option_num: 15,
  //     temp: "",
  //   },
  //   {
  //     name: "시계 문양",
  //     filename: "f_casque",
  //     grade: "f",
  //     type: "casque",
  //     base_option: "PS",
  //     base_option_num: 20,
  //     temp: "",
  //   },

  //   {
  //     name: "시계 문양",
  //     filename: "e_casque",
  //     grade: "e",
  //     type: "casque",
  //     base_option: "PS",
  //     base_option_num: 50,
  //     temp: "",
  //   },
  //   {
  //     name: "시계 문양",
  //     filename: "e_casque",
  //     grade: "e",
  //     type: "casque",
  //     base_option: "PS",
  //     base_option_num: 70,
  //     temp: "",
  //   },
  //   {
  //     name: "시계 문양",
  //     filename: "e_casque",
  //     grade: "e",
  //     type: "casque",
  //     base_option: "PS",
  //     base_option_num: 90,
  //     temp: "",
  //   },

  //   {
  //     name: "시계 문양",
  //     filename: "d_casque",
  //     grade: "d",
  //     type: "casque",
  //     base_option: "PS",
  //     base_option_num: 130,
  //     temp: "",
  //   },
  //   {
  //     name: "시계 문양",
  //     filename: "d_casque",
  //     grade: "d",
  //     type: "casque",
  //     base_option: "PS",
  //     base_option_num: 155,
  //     temp: "",
  //   },
  //   {
  //     name: "시계 문양",
  //     filename: "d_casque",
  //     grade: "d",
  //     type: "casque",
  //     base_option: "PS",
  //     base_option_num: 180,
  //     temp: "",
  //   },

  //   {
  //     name: "시계 문양",
  //     filename: "c_casque",
  //     grade: "c",
  //     type: "casque",
  //     base_option: "PS",
  //     base_option_num: 230,
  //     temp: "",
  //   },
  //   {
  //     name: "시계 문양",
  //     filename: "c_casque",
  //     grade: "c",
  //     type: "casque",
  //     base_option: "PS",
  //     base_option_num: 255,
  //     temp: "",
  //   },
  //   {
  //     name: "시계 문양",
  //     filename: "c_casque",
  //     grade: "c",
  //     type: "casque",
  //     base_option: "PS",
  //     base_option_num: 280,
  //     temp: "",
  //   },

  //   {
  //     name: "시계 문양",
  //     filename: "b_casque",
  //     grade: "b",
  //     type: "casque",
  //     base_option: "PS",
  //     base_option_num: 345,
  //     temp: "",
  //   },
  //   {
  //     name: "시계 문양",
  //     filename: "b_casque",
  //     grade: "b",
  //     type: "casque",
  //     base_option: "PS",
  //     base_option_num: 368,
  //     temp: "",
  //   },
  //   {
  //     name: "시계 문양",
  //     filename: "b_casque",
  //     grade: "b",
  //     type: "casque",
  //     base_option: "PS",
  //     base_option_num: 390,
  //     temp: "",
  //   },

  //   {
  //     name: "시계 문양",
  //     filename: "a_casque",
  //     grade: "a",
  //     type: "casque",
  //     base_option: "PS",
  //     base_option_num: 465,
  //     temp: "",
  //   },
  //   {
  //     name: "시계 문양",
  //     filename: "a_casque",
  //     grade: "a",
  //     type: "casque",
  //     base_option: "PS",
  //     base_option_num: 493,
  //     temp: "",
  //   },
  //   {
  //     name: "시계 문양",
  //     filename: "a_casque",
  //     grade: "a",
  //     type: "casque",
  //     base_option: "PS",
  //     base_option_num: 520,
  //     temp: "",
  //   },

  //   {
  //     name: "시계 문양",
  //     filename: "s_casque",
  //     grade: "s",
  //     type: "casque",
  //     base_option: "PS",
  //     base_option_num: 620,
  //     temp: "",
  //   },
  //   {
  //     name: "시계 문양",
  //     filename: "s_casque",
  //     grade: "s",
  //     type: "casque",
  //     base_option: "PS",
  //     base_option_num: 660,
  //     temp: "",
  //   },
  //   {
  //     name: "시계 문양",
  //     filename: "s_casque",
  //     grade: "s",
  //     type: "casque",
  //     base_option: "PS",
  //     base_option_num: 700,
  //     temp: "",
  //   },

  //   {
  //     name: "칼 문양",
  //     filename: "f_weapon",
  //     grade: "f",
  //     type: "weapon",
  //     base_option: "AP",
  //     base_option_num: 10,
  //     temp: "",
  //   },
  //   {
  //     name: "칼 문양",
  //     filename: "f_weapon",
  //     grade: "f",
  //     type: "weapon",
  //     base_option: "AP",
  //     base_option_num: 15,
  //     temp: "",
  //   },
  //   {
  //     name: "칼 문양",
  //     filename: "f_weapon",
  //     grade: "f",
  //     type: "weapon",
  //     base_option: "AP",
  //     base_option_num: 20,
  //     temp: "",
  //   },

  //   {
  //     name: "칼 문양",
  //     filename: "e_weapon",
  //     grade: "e",
  //     type: "weapon",
  //     base_option: "AP",
  //     base_option_num: 50,
  //     temp: "",
  //   },
  //   {
  //     name: "칼 문양",
  //     filename: "e_weapon",
  //     grade: "e",
  //     type: "weapon",
  //     base_option: "AP",
  //     base_option_num: 70,
  //     temp: "",
  //   },
  //   {
  //     name: "칼 문양",
  //     filename: "e_weapon",
  //     grade: "e",
  //     type: "weapon",
  //     base_option: "AP",
  //     base_option_num: 90,
  //     temp: "",
  //   },

  //   {
  //     name: "칼 문양",
  //     filename: "d_weapon",
  //     grade: "d",
  //     type: "weapon",
  //     base_option: "AP",
  //     base_option_num: 130,
  //     temp: "",
  //   },
  //   {
  //     name: "칼 문양",
  //     filename: "d_weapon",
  //     grade: "d",
  //     type: "weapon",
  //     base_option: "AP",
  //     base_option_num: 155,
  //     temp: "",
  //   },
  //   {
  //     name: "칼 문양",
  //     filename: "d_weapon",
  //     grade: "d",
  //     type: "weapon",
  //     base_option: "AP",
  //     base_option_num: 180,
  //     temp: "",
  //   },

  //   {
  //     name: "칼 문양",
  //     filename: "c_weapon",
  //     grade: "c",
  //     type: "weapon",
  //     base_option: "AP",
  //     base_option_num: 230,
  //     temp: "",
  //   },
  //   {
  //     name: "칼 문양",
  //     filename: "c_weapon",
  //     grade: "c",
  //     type: "weapon",
  //     base_option: "AP",
  //     base_option_num: 255,
  //     temp: "",
  //   },
  //   {
  //     name: "칼 문양",
  //     filename: "c_weapon",
  //     grade: "c",
  //     type: "weapon",
  //     base_option: "AP",
  //     base_option_num: 280,
  //     temp: "",
  //   },

  //   {
  //     name: "칼 문양",
  //     filename: "b_weapon",
  //     grade: "b",
  //     type: "weapon",
  //     base_option: "AP",
  //     base_option_num: 345,
  //     temp: "",
  //   },
  //   {
  //     name: "칼 문양",
  //     filename: "b_weapon",
  //     grade: "b",
  //     type: "weapon",
  //     base_option: "AP",
  //     base_option_num: 368,
  //     temp: "",
  //   },
  //   {
  //     name: "칼 문양",
  //     filename: "b_weapon",
  //     grade: "b",
  //     type: "weapon",
  //     base_option: "AP",
  //     base_option_num: 390,
  //     temp: "",
  //   },

  //   {
  //     name: "칼 문양",
  //     filename: "a_weapon",
  //     grade: "a",
  //     type: "weapon",
  //     base_option: "AP",
  //     base_option_num: 465,
  //     temp: "",
  //   },
  //   {
  //     name: "칼 문양",
  //     filename: "a_weapon",
  //     grade: "a",
  //     type: "weapon",
  //     base_option: "AP",
  //     base_option_num: 493,
  //     temp: "",
  //   },
  //   {
  //     name: "칼 문양",
  //     filename: "a_weapon",
  //     grade: "a",
  //     type: "weapon",
  //     base_option: "AP",
  //     base_option_num: 520,
  //     temp: "",
  //   },

  //   {
  //     name: "칼 문양",
  //     filename: "s_weapon",
  //     grade: "s",
  //     type: "weapon",
  //     base_option: "AP",
  //     base_option_num: 620,
  //     temp: "",
  //   },
  //   {
  //     name: "칼 문양",
  //     filename: "s_weapon",
  //     grade: "s",
  //     type: "weapon",
  //     base_option: "AP",
  //     base_option_num: 660,
  //     temp: "",
  //   },
  //   {
  //     name: "칼 문양",
  //     filename: "s_weapon",
  //     grade: "s",
  //     type: "weapon",
  //     base_option: "AP",
  //     base_option_num: 700,
  //     temp: "",
  //   },

  //   {
  //     name: "방패 문양",
  //     filename: "f_armor",
  //     grade: "f",
  //     type: "armor",
  //     base_option: "HP",
  //     base_option_num: 10,
  //     temp: "",
  //   },
  //   {
  //     name: "방패 문양",
  //     filename: "f_armor",
  //     grade: "f",
  //     type: "armor",
  //     base_option: "HP",
  //     base_option_num: 15,
  //     temp: "",
  //   },
  //   {
  //     name: "방패 문양",
  //     filename: "f_armor",
  //     grade: "f",
  //     type: "armor",
  //     base_option: "HP",
  //     base_option_num: 20,
  //     temp: "",
  //   },

  //   {
  //     name: "방패 문양",
  //     filename: "e_armor",
  //     grade: "e",
  //     type: "armor",
  //     base_option: "HP",
  //     base_option_num: 50,
  //     temp: "",
  //   },
  //   {
  //     name: "방패 문양",
  //     filename: "e_armor",
  //     grade: "e",
  //     type: "armor",
  //     base_option: "HP",
  //     base_option_num: 70,
  //     temp: "",
  //   },
  //   {
  //     name: "방패 문양",
  //     filename: "e_armor",
  //     grade: "e",
  //     type: "armor",
  //     base_option: "HP",
  //     base_option_num: 90,
  //     temp: "",
  //   },

  //   {
  //     name: "방패 문양",
  //     filename: "d_armor",
  //     grade: "d",
  //     type: "armor",
  //     base_option: "HP",
  //     base_option_num: 130,
  //     temp: "",
  //   },
  //   {
  //     name: "방패 문양",
  //     filename: "d_armor",
  //     grade: "d",
  //     type: "armor",
  //     base_option: "HP",
  //     base_option_num: 155,
  //     temp: "",
  //   },
  //   {
  //     name: "방패 문양",
  //     filename: "d_armor",
  //     grade: "d",
  //     type: "armor",
  //     base_option: "HP",
  //     base_option_num: 180,
  //     temp: "",
  //   },

  //   {
  //     name: "방패 문양",
  //     filename: "c_armor",
  //     grade: "c",
  //     type: "armor",
  //     base_option: "HP",
  //     base_option_num: 230,
  //     temp: "",
  //   },
  //   {
  //     name: "방패 문양",
  //     filename: "c_armor",
  //     grade: "c",
  //     type: "armor",
  //     base_option: "HP",
  //     base_option_num: 255,
  //     temp: "",
  //   },
  //   {
  //     name: "방패 문양",
  //     filename: "c_armor",
  //     grade: "c",
  //     type: "armor",
  //     base_option: "HP",
  //     base_option_num: 280,
  //     temp: "",
  //   },

  //   {
  //     name: "방패 문양",
  //     filename: "b_armor",
  //     grade: "b",
  //     type: "armor",
  //     base_option: "HP",
  //     base_option_num: 345,
  //     temp: "",
  //   },
  //   {
  //     name: "방패 문양",
  //     filename: "b_armor",
  //     grade: "b",
  //     type: "armor",
  //     base_option: "HP",
  //     base_option_num: 368,
  //     temp: "",
  //   },
  //   {
  //     name: "방패 문양",
  //     filename: "b_armor",
  //     grade: "b",
  //     type: "armor",
  //     base_option: "HP",
  //     base_option_num: 390,
  //     temp: "",
  //   },

  //   {
  //     name: "방패 문양",
  //     filename: "a_armor",
  //     grade: "a",
  //     type: "armor",
  //     base_option: "HP",
  //     base_option_num: 465,
  //     temp: "",
  //   },
  //   {
  //     name: "방패 문양",
  //     filename: "a_armor",
  //     grade: "a",
  //     type: "armor",
  //     base_option: "HP",
  //     base_option_num: 493,
  //     temp: "",
  //   },
  //   {
  //     name: "방패 문양",
  //     filename: "a_armor",
  //     grade: "a",
  //     type: "armor",
  //     base_option: "HP",
  //     base_option_num: 520,
  //     temp: "",
  //   },
  //   {
  //     name: "방패 문양",
  //     filename: "s_armor",
  //     grade: "s",
  //     type: "armor",
  //     base_option: "HP",
  //     base_option_num: 620,
  //     temp: "",
  //   },
  //   {
  //     name: "방패 문양",
  //     filename: "s_armor",
  //     grade: "s",
  //     type: "armor",
  //     base_option: "HP",
  //     base_option_num: 660,
  //     temp: "",
  //   },
  //   {
  //     name: "방패 문양",
  //     filename: "s_armor",
  //     grade: "s",
  //     type: "armor",
  //     base_option: "HP",
  //     base_option_num: 700,
  //     temp: "",
  //   },

  //   {
  //     name: "날개 문양",
  //     filename: "f_shoes",
  //     grade: "f",
  //     type: "shoes",
  //     base_option: "SP",
  //     base_option_num: 10,
  //     temp: "",
  //   },
  //   {
  //     name: "날개 문양",
  //     filename: "f_shoes",
  //     grade: "f",
  //     type: "shoes",
  //     base_option: "SP",
  //     base_option_num: 15,
  //     temp: "",
  //   },
  //   {
  //     name: "날개 문양",
  //     filename: "f_shoes",
  //     grade: "f",
  //     type: "shoes",
  //     base_option: "SP",
  //     base_option_num: 20,
  //     temp: "",
  //   },

  //   {
  //     name: "날개 문양",
  //     filename: "e_shoes",
  //     grade: "e",
  //     type: "shoes",
  //     base_option: "SP",
  //     base_option_num: 50,
  //     temp: "",
  //   },
  //   {
  //     name: "날개 문양",
  //     filename: "e_shoes",
  //     grade: "e",
  //     type: "shoes",
  //     base_option: "SP",
  //     base_option_num: 70,
  //     temp: "",
  //   },
  //   {
  //     name: "날개 문양",
  //     filename: "e_shoes",
  //     grade: "e",
  //     type: "shoes",
  //     base_option: "SP",
  //     base_option_num: 90,
  //     temp: "",
  //   },

  //   {
  //     name: "날개 문양",
  //     filename: "d_shoes",
  //     grade: "d",
  //     type: "shoes",
  //     base_option: "SP",
  //     base_option_num: 130,
  //     temp: "",
  //   },
  //   {
  //     name: "날개 문양",
  //     filename: "d_shoes",
  //     grade: "d",
  //     type: "shoes",
  //     base_option: "SP",
  //     base_option_num: 155,
  //     temp: "",
  //   },
  //   {
  //     name: "날개 문양",
  //     filename: "d_shoes",
  //     grade: "d",
  //     type: "shoes",
  //     base_option: "SP",
  //     base_option_num: 180,
  //     temp: "",
  //   },

  //   {
  //     name: "날개 문양",
  //     filename: "c_shoes",
  //     grade: "c",
  //     type: "shoes",
  //     base_option: "SP",
  //     base_option_num: 230,
  //     temp: "",
  //   },
  //   {
  //     name: "날개 문양",
  //     filename: "c_shoes",
  //     grade: "c",
  //     type: "shoes",
  //     base_option: "SP",
  //     base_option_num: 255,
  //     temp: "",
  //   },
  //   {
  //     name: "날개 문양",
  //     filename: "c_shoes",
  //     grade: "c",
  //     type: "shoes",
  //     base_option: "SP",
  //     base_option_num: 280,
  //     temp: "",
  //   },

  //   {
  //     name: "날개 문양",
  //     filename: "b_shoes",
  //     grade: "b",
  //     type: "shoes",
  //     base_option: "SP",
  //     base_option_num: 345,
  //     temp: "",
  //   },
  //   {
  //     name: "날개 문양",
  //     filename: "b_shoes",
  //     grade: "b",
  //     type: "shoes",
  //     base_option: "SP",
  //     base_option_num: 368,
  //     temp: "",
  //   },
  //   {
  //     name: "날개 문양",
  //     filename: "b_shoes",
  //     grade: "b",
  //     type: "shoes",
  //     base_option: "SP",
  //     base_option_num: 390,
  //     temp: "",
  //   },

  //   {
  //     name: "날개 문양",
  //     filename: "a_shoes",
  //     grade: "a",
  //     type: "shoes",
  //     base_option: "SP",
  //     base_option_num: 465,
  //     temp: "",
  //   },
  //   {
  //     name: "날개 문양",
  //     filename: "a_shoes",
  //     grade: "a",
  //     type: "shoes",
  //     base_option: "SP",
  //     base_option_num: 493,
  //     temp: "",
  //   },
  //   {
  //     name: "날개 문양",
  //     filename: "a_shoes",
  //     grade: "a",
  //     type: "shoes",
  //     base_option: "SP",
  //     base_option_num: 520,
  //     temp: "",
  //   },

  //   {
  //     name: "날개 문양",
  //     filename: "s_shoes",
  //     grade: "s",
  //     type: "shoes",
  //     base_option: "SP",
  //     base_option_num: 620,
  //     temp: "",
  //   },
  //   {
  //     name: "날개 문양",
  //     filename: "s_shoes",
  //     grade: "s",
  //     type: "shoes",
  //     base_option: "SP",
  //     base_option_num: 660,
  //     temp: "",
  //   },
  //   {
  //     name: "날개 문양",
  //     filename: "s_shoes",
  //     grade: "s",
  //     type: "shoes",
  //     base_option: "SP",
  //     base_option_num: 700,
  //     temp: "",
  //   },
];
